# Generated by Django 5.1.4 on 2025-01-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("player", "Игрок"),
                    ("manager", "Менеджер"),
                    ("influencer", "Блогер"),
                    ("marketer", "Маркетолог"),
                    ("copywriter", "Копирайтер"),
                    ("other", "другое"),
                ],
                default="player",
                max_length=20,
                verbose_name="роль",
            ),
        ),
    ]
